### ISSUE TITLE
Doc improvement: Add a short introduction to the Messaging documentation

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.messaging#278]
The Arcus Messaging 'Welcome' page in the documentation describes how to install the Messaging library and gives a bullet point list of it's features
![image](https://user-images.githubusercontent.com/3605786/166421629-47352bb5-c228-4c07-8adc-0387301cf8a5.png)

However, I think it would be great to add a small 'Introduction' section just before the `Installation` section.
This Introduction paragraph could describe what Arcus.Messaging is about and why you want to use it.   A few sentences would be enough.

**Comment by fgheysels** [comment]
I was rather thinking of adding a short description to each (dedicated) readme that is present for each project.
We can add this information to the global welcome page as well, but I think it is good to have it on your 'project landing' page as well.

**Comment by stijnmoreels** [comment]
Well, that's a bit confusing, as the screenshot is about the global welcome page 😄 . Not sure if I understand the 'dedicated' README, as we are linking all to the same README of the project in the root of the repo. As for the 'landing page', you mean on NuGet? Because this README reference is only so that there's something nice to show on NuGet.

**Comment by fgheysels** [comment]
The screenshot is for arcus messaging ?

**Comment by stijnmoreels** [comment]
> The screenshot is for arcus messaging ?

Yes, I meant the global introduction page of Arcus Messaging, not the README that is present in projects on NuGet.
