### ISSUE TITLE
Provide Azure Service Bus plugin for managing serialization information

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.messaging#34]
Provide Azure Service Bus plugin for managing serialization information by adding it to the message context and interpreting it on read.

**Comment by tomkerkhove** [comment]
This will not be possible for sending but it would for receiving, or would and extension be better?
In the end, we'll pull the required info from the message headers and wrap it in an object.

What do you think @stijnmoreels?

**Comment by stijnmoreels** [comment]
I think we'll have the same problem here as with the correlation. Eventually, we want to enrich the messaging context, and that's not available in the plugin; which would lead us again to some extension or passing allong of the information.

An extension on the message seems more appropriate for this, since we want to set a context that's/can-be different for each message.

**Comment by stijnmoreels** [comment]
About which serialization headers are we talking about? Encoding?

**Comment by tomkerkhove** [comment]
Nevermind, I was confusing it with correlation.

**Comment by stijnmoreels** [comment]
What can we decribe as serialization information, that we can extract?

**Comment by tomkerkhove** [comment]
These 2: https://github.com/arcus-azure/arcus.messaging/blob/master/src/Arcus.Messaging.ServiceBus.Core/Extensions/ObjectExtensions.cs#L33

**Comment by stijnmoreels** [comment]
Plugins are for now (I think) not yet supported in the new Azure SDK. So, it depends on whether or not we continue to support the 'old' version or not. If not, we should wait till it's supported.

**Comment by tomkerkhove** [comment]
Let's just kill this issue :)
